### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by steamfoundry**
Just minor fixes and a missing link

TeamMcFly
HoverGames 2022

### CODE REVIEW

**Comment by steamfoundry** [comment]
Can you review @igalloway

**Comment by igalloway** [comment]
In the readme, you are removing AI/ML.
NavQPlus includes a neural net accelerator NPU. That's why it was mentioned

**Comment by steamfoundry** [comment]
Can you double check please?   It should be removing a duplicate bottom line (line 62) but leaving the top line that included AI/ML.

**Comment by igalloway** [comment]
Oh yes! That looks correct.

**Pull request merged**
